name: Update docs

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version of docs, for example 0.1.x"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
      -   name: Set up python 3
          uses: actions/setup-python@v2
          with:
            python-version: 3.x
      -   name: Install mkdocs and mike
          run: pip install mkdocs-material mike
      - name: Setup doc deploy
          run: |
            git config --global user.name Docs deploy
            git config --global user.email docs@dummy.bot.com
      -   name: Deploy docs
          run: mike deploy --push --force ${{ github.event.inputs.version }}
