name: Update docs

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version of docs, for example 0.1.x"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike
      - name: Set up git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          token: ${{ secrets.USER_TOKEN }}
      - run: mike deploy --push --update-aliases ${{ github.event.inputs.version }}
